[project]
name = "estimation-fastapi-svc"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic==0.75.0",
    "boto3==1.42.27",
    "celery>=5.6.3",
    "fastapi>=0.136.0",
    "pikepdf==10.3.0",
    "pydantic-settings>=2.14.0",
    "pypdf>=6.10.2",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.26",
    "redis>=5.0.0,<6.5",
    "uvicorn>=0.45.0",
    "celery[redis]>=5.4.0",
    "supabase>=2.12.0",
]
